
groups:
- name: node_cpu_usage
  rules:
  - alert: cpu_usage
    expr: round(100-(avg(irate(node_cpu_seconds_total{mode="idel",job="expo_nodes"}[5m]))by(instance)*100))>50
    for: 15s
    labels:
      severity: warning
      team: node
    annotations:
      summary: "{{ $labels.instance }} CPU USAGE HIGH!"
      description: "{{ $labels.instance }} CPU使用率超过百分之50,请注意关注！！！当前使用率为{{ $value }}%"
